#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

usage() {
  cat >&2 <<EOF
Usage: $0 <name> <repo>

  <name>   Project slug used during provisioning.
  <repo>   GitHub SSH URL (e.g. git@github.com:org/repo.git).

  Clones <repo> into /home/deploy/projects/<name>/ using the deploy key
  generated by provision-project.sh (expected at ~/.ssh/<name>_deploy_key).

Examples:
  $0 meu-projeto git@github.com:org/meu-projeto.git
EOF
  exit 1
}

[ $# -lt 2 ] && usage

NAME="$1"
REPO="$2"

DEPLOY_KEY="$HOME/.ssh/${NAME}_deploy_key"
DEST="/home/deploy/projects/${NAME}"

if [ ! -f "$DEPLOY_KEY" ]; then
  echo "Error: deploy key not found at $DEPLOY_KEY" >&2
  echo "Run provision-project.sh with --deploy-key first." >&2
  exit 1
fi

if [ -d "$DEST" ]; then
  echo "Error: destination already exists: $DEST" >&2
  exit 1
fi

mkdir -p "$(dirname "$DEST")"

echo "[clone] Cloning $REPO into $DEST..."
GIT_SSH_COMMAND="ssh -i $DEPLOY_KEY -o StrictHostKeyChecking=no" \
  git clone "$REPO" "$DEST"

echo "[clone] Done! Repository cloned to $DEST"
